services:
  controller:
    build:
      context: .
      dockerfile: ./cmd/controller/Dockerfile
    container_name: controller
    ports:
      - "8080:8080"
    networks:
      - temp
    environment:
      - DOCKER_NETWORK=temp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true

  loadbalancer:
    build:
      context: .
      dockerfile: ./cmd/loadbalancer/Dockerfile
    container_name: loadbalancer
    ports:
      - "9001:9001"
    networks:
      - temp
  
  clinet:
    build:
      context: .
      dockerfile: ./cmd/client/Dockerfile
    container_name: client
    networks:
      - temp
    environment:
      - DOCKER_NETWORK=temp

  node:
    build:
      context: .
      dockerfile: ./cmd/node/Dockerfile

networks:
  temp:
    driver: bridge